BookStore/Components/TopBooksViewComponent.cs
using BookStore.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

BookStore/Views/Home/AboutUs.cshtml
<h1>This is about page of application</h1>

BookStore/Views/Home/ContactUs.cshtml
<h1>This is contact us page</h1>

BookStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
@*@model IEnumerable<BookModel>*@
<section class=" text-center">
    <div class="container">
        <h1>Welcome to bookStore</h1>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>
</section>
<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top Books</h3>
        @*@await Component.InvokeAsync("TopBooks")*@  
        <vc:top-books count="3"></vc:top-books>
    </div>
</div>